### ISSUE TITLE
bottom pane (program logs) output overlaps w/ AccountView

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#227] opened 2022-07-13 22:27 UTC
kind of a goofy bug, if I drag log view pane up in a tall window with chatty net, it collides w/ the accounts

https://user-images.githubusercontent.com/1476820/178847573-83a8c0ed-b8d3-454c-80ed-ca988c6f6805.mov

**Comment by SvenDowideit** [comment] 2022-07-13 22:39
dupe of #179

**Comment by nathanleclaire** [comment] 2022-07-13 23:54
I don't think so, this is that in `Account` endpoint logs mix with changes view if you pull the `<Split>` up, #179 is that the logs will spill into the bottom of the screen on the validator page and force a scroll bar

**Closed** 2022-07-18 21:57 UTC
Labels: bug

**Comment by nathanleclaire** [comment] 2022-07-19 00:54
to show the visual on this issue --

<img width="1210" alt="Screen Shot 2022-07-18 at 8 54 09 PM" src="https://user-images.githubusercontent.com/1476820/179641004-db825bca-fabd-40d8-a8da-353f7dea26bf.png">
